name = "hello2024-backend"
main = "src/index.js"
compatibility_date = "2024-02-08"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/kv
[[kv_namespaces]]
binding = "KV"
id = "7f00eb52a7a44db786aa43c56bb693f1"

[dev]
ip = "0.0.0.0"
